version: "3"

services:
    web:
        container_name: wagtail
        restart: always
        build: ./app
        image: elbrus/wagtail
        expose:
            - "8000"
        volumes:
            - ./app:/app
            - static_volume:/vol/web/static
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        links:
            - postgres:postgres
        depends_on:
            - postgres
    nginx:
        container_name: nginx
        restart: always
        build: ./nginx
        image: elbrus/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static_volume:/static
        volumes_from:
            - web
        links:
            - web:web
        depends_on:
            - web
    postgres:
        container_name: postgres
        restart: always
        build: ./postgres
        image: elbrus/postgres
        volumes:
            - ./db_backup:/db_backup
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"

volumes:
    static_volume:
