apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: postgres
          image: elbrus/postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgdb
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pguser2
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpwd 
                  key: POSTGRES_PASSWORD
        - name: wagtail
          image: elbrus/wagtail
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: djsecretkey
                  key: SECRET_KEY
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: pghost
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pgdb
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pguser2
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpwd 
                  key: POSTGRES_PASSWORD

---

apiVersion: v1
kind: Service 
metadata:
  name: web-service 
spec:
  type: LoadBalancer
  ports:
    - name: http 
      port: 80
      targetPort: 8000
    - name: db 
      port: 5432
      targetPort: 5432
  selector:
    app: web